
services:
  pgdb:
    image: postgres:17.2
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: gosampledb
    volumes:
      - ./postgresdb:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "6432:5432"
    restart: always
    networks:
      - goapi_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
      start_period: 10s

  goapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_sample_api
    ports:
      - "7070:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=pgdb
      - DB_PORT=5432
      - DB_NAME=gosampledb
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_SSLMODE=disable
      - DB_TIMEZONE=UTC
      - DB_CONNECT_TIMEOUT=5
      - JWT_SECRET=verysecret
      - JWT_ISSUER=example.com
      - JWT_AUDIENCE=example.com
      - COOKIE_DOMAIN=localhost
      - DOMAIN=example.com
      - API_KEY=b41447e6319d1cd467306735632ba733
    depends_on:
      pgdb:
        condition: service_healthy
    restart: always
    networks:
      - goapi_network

networks:
  goapi_network:
    driver: bridge

volumes:
  postgresdb:
